### ISSUE TITLE
 Automatic response in the group! I NEED TO BLOCK!

### ISSUE THREAD

**Issue by victorfreire100** [boehlergerman/WappBot#11]
how to disable replies in groups?

**Comment by boehlergerman** [comment]
Hello @victorfreire100, what you could do is check the object that returns the following [function](https://github.com/boehlergerman/WappBot/blob/ac30aeb7079140170883e9c49326106d7565e025/wappbot.js#L285), inside it there is a property that says if the chat is a group or not.

![image](https://user-images.githubusercontent.com/27646282/95003071-9a3d7000-05b1-11eb-824e-a58e9553c834.png)

**Comment by victorfreire100** [comment]
Hey !! thank you!

but I still haven't got it, the bot keeps sending a group message! :(

**Comment by boehlergerman** [comment]
> Hey !! thank you!
> 
> but I still haven't got it, the bot keeps sending a group message! :(

ohhh, sorry, I thought you had a project fork and wanted to implement it in your bot, let me see if I can implement this functionality, within this project.
Possibly add a property within the [settings](https://github.com/boehlergerman/WappBot/blob/ac30aeb7079140170883e9c49326106d7565e025/wappbot.js#L5), which by default does not block the groups, you can put it in true for your use case, you think?

**Comment by victorfreire100** [comment]
I want the bot not to respond in groups. just chats. But I'm having a lot of problems

sorry if i'm taking your time !!

**Comment by boehlergerman** [comment]
No problem!! let me implement this functionality and when I have it ready I'll let you know.

**Comment by victorfreire100** [comment]
thank youuuuuuuuu very much!!!


I love you!! hahahahaah

**Comment by boehlergerman** [comment]
the feature was added to the repository with the PR: #13  for any other doubt or suggestion don't hesitate to open a new issue!
