### ISSUE TITLE
I added a new post request to the source code, but I cannot get the return value of the post. What did I do wrong? Below is a screenshot of my debugging

### ISSUE THREAD

**Issue by 286844626** [boehlergerman/WappBot#12]
![image](https://user-images.githubusercontent.com/34543121/94509396-bc985c00-0246-11eb-937c-622a4bd66e4f.png)
![image](https://user-images.githubusercontent.com/34543121/94509423-cb7f0e80-0246-11eb-839b-b9bab6add3b7.png)
![image](https://user-images.githubusercontent.com/34543121/94509429-cfab2c00-0246-11eb-89dc-868f46ea66c9.png)

**Comment by boehlergerman** [comment]
Hi @286844626, could you tell me what you are trying to do? to understand the context of what you need, thank you!

you can see an example of an http request in the following line: [http request](https://github.com/boehlergerman/WappBot/blob/ac30aeb7079140170883e9c49326106d7565e025/wappbot.js#L371)
